project_name: browser-tlsaudit-service
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - 
    main: ./cmd/service/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    github:
      owner: adedayo
      name: homebrew-tap
    homepage: "https://github.com/adedayo/browser-tls-audit"
    description: "This is a simple services to collect TLS capabilities of a client browser"
